name: DamageNumbers
version: '1.0-SNAPSHOT'
main: carnage.damageNumbers.DamageNumbers
api-version: '1.21'
depend: [packetevents]
author: FinalCarnage942
commands:
  damagenumbers:
    description: DamageNumbers commands
    usage: /<command> test <hit|crit|heal>
    aliases: [dg]
    permission: damagenumbers.test
  dnreload:
    description: Reload DamageNumbers configuration
    usage: /dnreload
    permission: damagenumbers.reload

permissions:
  damagenumbers.test:
    description: Allows testing damage holograms
    default: op
  damagenumbers.reload:
    description: Allows reloading damage numbers config
    default: op